"""add chat_id to unread messages

Revision ID: 6cea015355c2
Revises: 21c74283645d
Create Date: 2024-02-13 23:05:51.039209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cea015355c2'
down_revision: Union[str, None] = '21c74283645d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unread_messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'unread_messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unread_messages', type_='foreignkey')
    op.drop_column('unread_messages', 'chat_id')
    # ### end Alembic commands ###
